// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServerManagement2._0.Data;

#nullable disable

namespace ServerManagement2._0.Migrations
{
    [DbContext(typeof(ServerManagementContext))]
    [Migration("20250603062040_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorSVM.Models.Server", b =>
                {
                    b.Property<int>("ServerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServerID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServerID");

                    b.ToTable("Servers");

                    b.HasData(
                        new
                        {
                            ServerID = 1,
                            City = "Toronto",
                            IsOnline = false,
                            Name = "Server1"
                        },
                        new
                        {
                            ServerID = 2,
                            City = "Toronto",
                            IsOnline = false,
                            Name = "Server2"
                        },
                        new
                        {
                            ServerID = 3,
                            City = "Toronto",
                            IsOnline = true,
                            Name = "Server3"
                        },
                        new
                        {
                            ServerID = 4,
                            City = "Toronto",
                            IsOnline = true,
                            Name = "Server4"
                        },
                        new
                        {
                            ServerID = 5,
                            City = "Montreal",
                            IsOnline = true,
                            Name = "Server5"
                        },
                        new
                        {
                            ServerID = 6,
                            City = "Montreal",
                            IsOnline = true,
                            Name = "Server6"
                        },
                        new
                        {
                            ServerID = 7,
                            City = "Montreal",
                            IsOnline = false,
                            Name = "Server7"
                        },
                        new
                        {
                            ServerID = 8,
                            City = "Ottawa",
                            IsOnline = false,
                            Name = "Server8"
                        },
                        new
                        {
                            ServerID = 9,
                            City = "Ottawa",
                            IsOnline = false,
                            Name = "Server9"
                        },
                        new
                        {
                            ServerID = 10,
                            City = "Calgary",
                            IsOnline = true,
                            Name = "Server10"
                        },
                        new
                        {
                            ServerID = 11,
                            City = "Calgary",
                            IsOnline = true,
                            Name = "Server11"
                        },
                        new
                        {
                            ServerID = 12,
                            City = "Halifax",
                            IsOnline = false,
                            Name = "Server12"
                        },
                        new
                        {
                            ServerID = 13,
                            City = "Halifax",
                            IsOnline = true,
                            Name = "Server13"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
